In [14]:
import numpy as np

x = np.random.rand(4,6)

In [15]:
print(x)

[[0.47185969 0.02940631 0.50547945 0.32471153 0.02484353 0.41491987]
 [0.57186166 0.54324774 0.12796837 0.99306813 0.11425716 0.4395697 ]
 [0.12481853 0.45557046 0.15473486 0.54692324 0.87992118 0.99925755]
 [0.29414971 0.18059535 0.43678304 0.74286095 0.3639652  0.11646427]]


In [17]:
x.shape[0]

4

In [4]:
y = np.clip(x,0.3,0.5)

In [5]:
y

array([[0.3       , 0.3       , 0.3       , 0.5       ],
       [0.45762055, 0.3       , 0.40176514, 0.5       ],
       [0.5       , 0.3       , 0.5       , 0.5       ],
       [0.3       , 0.5       , 0.46646518, 0.5       ]])

In [6]:
x = np.array([3,6,9,3])

In [7]:
y = np.array(x)

In [8]:
y

array([3, 6, 9, 3])

In [18]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
c = np.array([0,1,2])

In [22]:
c

array([0, 1, 2])

In [26]:
m[:,1] = m[:,1]*c

In [27]:
m

array([[ 1,  0,  3],
       [ 4,  5,  6],
       [ 7, 16,  9]])

In [41]:
LAMBDA = 0.8
decay_factor = np.array([i for i in (LAMBDA**n for n in reversed(range(1, 25)))])


In [42]:
decay_factor

array([0.00472237, 0.00590296, 0.0073787 , 0.00922337, 0.01152922,
       0.01441152, 0.0180144 , 0.022518  , 0.0281475 , 0.03518437,
       0.04398047, 0.05497558, 0.06871948, 0.08589935, 0.10737418,
       0.13421773, 0.16777216, 0.2097152 , 0.262144  , 0.32768   ,
       0.4096    , 0.512     , 0.64      , 0.8       ])