In [17]:
import numpy as np

In [18]:
x = np.ones((3,5))

In [19]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
transition_rec = [2,2,2,2,2]
index = 0
np.insert(x, index, transition_rec,0)

array([[2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
y = y**2

In [9]:
x[1,:] = y

In [10]:
x

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  4.,  9., 16.],
       [ 0.,  0.,  0.,  0.,  0.]])